name: Canary Releases

on: [pull_request]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 14
        uses: actions/setup-node@master
        with:
          node-version: 14

      - name: Bob, check the repo
        id: bob
        uses: 'kamilkisiela/bob@master'
      - name: Bob, check Build
        id: bob-build
        uses: 'kamilkisiela/bob@master'
        with:
          command: build

      - uses: actions/cache@v2
        name: Cache node_modules
        if: steps.bob.outputs.dirty == 'true'
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install
        if: steps.bob.outputs.dirty == 'true'
        run: yarn

      - name: Build
        if: steps.bob-build.outputs.dirty == 'true'
        run: yarn affected:build
      
      - name: Pack
        if: steps.bob-build.outputs.dirty == 'true'
        run: yarn bob pack-flat --commit $GITHUB_RUN_ID

      # PUBLISH_PACKAGES

      - name: "Publish core"
        uses: actions/upload-artifact@v2
        if: steps.bob-build.outputs.dirty == 'true'
        with:
          name: core.tgz
          path: .bob-packed/graphql-inspector-core-0.0.0-canary-${{ GITHUB_RUN_ID }}.tar.gz
          retention-days: 7
          if-no-files-found: ignore
  

      - name: "Publish logger"
        uses: actions/upload-artifact@v2
        if: steps.bob-build.outputs.dirty == 'true'
        with:
          name: logger.tgz
          path: .bob-packed/graphql-inspector-logger-0.0.0-canary-${{ GITHUB_RUN_ID }}.tar.gz
          retention-days: 7
          if-no-files-found: ignore
  

      - name: "Publish ci"
        uses: actions/upload-artifact@v2
        if: steps.bob-build.outputs.dirty == 'true'
        with:
          name: ci.tgz
          path: .bob-packed/graphql-inspector-ci-0.0.0-canary-${{ GITHUB_RUN_ID }}.tar.gz
          retention-days: 7
          if-no-files-found: ignore
  

      - name: "Publish cli"
        uses: actions/upload-artifact@v2
        if: steps.bob-build.outputs.dirty == 'true'
        with:
          name: cli.tgz
          path: .bob-packed/graphql-inspector-cli-0.0.0-canary-${{ GITHUB_RUN_ID }}.tar.gz
          retention-days: 7
          if-no-files-found: ignore
  

      - name: "Publish config"
        uses: actions/upload-artifact@v2
        if: steps.bob-build.outputs.dirty == 'true'
        with:
          name: config.tgz
          path: .bob-packed/graphql-inspector-config-0.0.0-canary-${{ GITHUB_RUN_ID }}.tar.gz
          retention-days: 7
          if-no-files-found: ignore
  

      - name: "Publish commands"
        uses: actions/upload-artifact@v2
        if: steps.bob-build.outputs.dirty == 'true'
        with:
          name: commands.tgz
          path: .bob-packed/graphql-inspector-commands-0.0.0-canary-${{ GITHUB_RUN_ID }}.tar.gz
          retention-days: 7
          if-no-files-found: ignore
  

      - name: "Publish loaders"
        uses: actions/upload-artifact@v2
        if: steps.bob-build.outputs.dirty == 'true'
        with:
          name: loaders.tgz
          path: .bob-packed/graphql-inspector-loaders-0.0.0-canary-${{ GITHUB_RUN_ID }}.tar.gz
          retention-days: 7
          if-no-files-found: ignore
  

      - name: "Publish github"
        uses: actions/upload-artifact@v2
        if: steps.bob-build.outputs.dirty == 'true'
        with:
          name: github.tgz
          path: .bob-packed/graphql-inspector-github-0.0.0-canary-${{ GITHUB_RUN_ID }}.tar.gz
          retention-days: 7
          if-no-files-found: ignore
  

      - name: "Publish action"
        uses: actions/upload-artifact@v2
        if: steps.bob-build.outputs.dirty == 'true'
        with:
          name: action.tgz
          path: .bob-packed/graphql-inspector-action-0.0.0-canary-${{ GITHUB_RUN_ID }}.tar.gz
          retention-days: 7
          if-no-files-found: ignore
  

      - name: "Publish code-loader"
        uses: actions/upload-artifact@v2
        if: steps.bob-build.outputs.dirty == 'true'
        with:
          name: code-loader.tgz
          path: .bob-packed/graphql-inspector-code-loader-0.0.0-canary-${{ GITHUB_RUN_ID }}.tar.gz
          retention-days: 7
          if-no-files-found: ignore
  

      - name: "Publish git-loader"
        uses: actions/upload-artifact@v2
        if: steps.bob-build.outputs.dirty == 'true'
        with:
          name: git-loader.tgz
          path: .bob-packed/graphql-inspector-git-loader-0.0.0-canary-${{ GITHUB_RUN_ID }}.tar.gz
          retention-days: 7
          if-no-files-found: ignore
  

      - name: "Publish github-loader"
        uses: actions/upload-artifact@v2
        if: steps.bob-build.outputs.dirty == 'true'
        with:
          name: github-loader.tgz
          path: .bob-packed/graphql-inspector-github-loader-0.0.0-canary-${{ GITHUB_RUN_ID }}.tar.gz
          retention-days: 7
          if-no-files-found: ignore
  

      - name: "Publish graphql-loader"
        uses: actions/upload-artifact@v2
        if: steps.bob-build.outputs.dirty == 'true'
        with:
          name: graphql-loader.tgz
          path: .bob-packed/graphql-inspector-graphql-loader-0.0.0-canary-${{ GITHUB_RUN_ID }}.tar.gz
          retention-days: 7
          if-no-files-found: ignore
  

      - name: "Publish json-loader"
        uses: actions/upload-artifact@v2
        if: steps.bob-build.outputs.dirty == 'true'
        with:
          name: json-loader.tgz
          path: .bob-packed/graphql-inspector-json-loader-0.0.0-canary-${{ GITHUB_RUN_ID }}.tar.gz
          retention-days: 7
          if-no-files-found: ignore
  

      - name: "Publish url-loader"
        uses: actions/upload-artifact@v2
        if: steps.bob-build.outputs.dirty == 'true'
        with:
          name: url-loader.tgz
          path: .bob-packed/graphql-inspector-url-loader-0.0.0-canary-${{ GITHUB_RUN_ID }}.tar.gz
          retention-days: 7
          if-no-files-found: ignore
  

      - name: "Publish diff-command"
        uses: actions/upload-artifact@v2
        if: steps.bob-build.outputs.dirty == 'true'
        with:
          name: diff-command.tgz
          path: .bob-packed/graphql-inspector-diff-command-0.0.0-canary-${{ GITHUB_RUN_ID }}.tar.gz
          retention-days: 7
          if-no-files-found: ignore
  

      - name: "Publish docs-command"
        uses: actions/upload-artifact@v2
        if: steps.bob-build.outputs.dirty == 'true'
        with:
          name: docs-command.tgz
          path: .bob-packed/graphql-inspector-docs-command-0.0.0-canary-${{ GITHUB_RUN_ID }}.tar.gz
          retention-days: 7
          if-no-files-found: ignore
  

      - name: "Publish serve-command"
        uses: actions/upload-artifact@v2
        if: steps.bob-build.outputs.dirty == 'true'
        with:
          name: serve-command.tgz
          path: .bob-packed/graphql-inspector-serve-command-0.0.0-canary-${{ GITHUB_RUN_ID }}.tar.gz
          retention-days: 7
          if-no-files-found: ignore
  

      - name: "Publish coverage-command"
        uses: actions/upload-artifact@v2
        if: steps.bob-build.outputs.dirty == 'true'
        with:
          name: coverage-command.tgz
          path: .bob-packed/graphql-inspector-coverage-command-0.0.0-canary-${{ GITHUB_RUN_ID }}.tar.gz
          retention-days: 7
          if-no-files-found: ignore
  

      - name: "Publish validate-command"
        uses: actions/upload-artifact@v2
        if: steps.bob-build.outputs.dirty == 'true'
        with:
          name: validate-command.tgz
          path: .bob-packed/graphql-inspector-validate-command-0.0.0-canary-${{ GITHUB_RUN_ID }}.tar.gz
          retention-days: 7
          if-no-files-found: ignore
  

      - name: "Publish introspect-command"
        uses: actions/upload-artifact@v2
        if: steps.bob-build.outputs.dirty == 'true'
        with:
          name: introspect-command.tgz
          path: .bob-packed/graphql-inspector-introspect-command-0.0.0-canary-${{ GITHUB_RUN_ID }}.tar.gz
          retention-days: 7
          if-no-files-found: ignore
  

      - name: "Publish similar-command"
        uses: actions/upload-artifact@v2
        if: steps.bob-build.outputs.dirty == 'true'
        with:
          name: similar-command.tgz
          path: .bob-packed/graphql-inspector-similar-command-0.0.0-canary-${{ GITHUB_RUN_ID }}.tar.gz
          retention-days: 7
          if-no-files-found: ignore
  

      - name: "Publish graphql-cli-common"
        uses: actions/upload-artifact@v2
        if: steps.bob-build.outputs.dirty == 'true'
        with:
          name: graphql-cli-common.tgz
          path: .bob-packed/graphql-inspector-graphql-cli-common-0.0.0-canary-${{ GITHUB_RUN_ID }}.tar.gz
          retention-days: 7
          if-no-files-found: ignore
  

      - name: "Publish testing"
        uses: actions/upload-artifact@v2
        if: steps.bob-build.outputs.dirty == 'true'
        with:
          name: testing.tgz
          path: .bob-packed/graphql-inspector-testing-0.0.0-canary-${{ GITHUB_RUN_ID }}.tar.gz
          retention-days: 7
          if-no-files-found: ignore
  